"""SQLAlchemy models representing the MariaDB schema."""

from __future__ import annotations

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    UniqueConstraint,
)
from sqlalchemy.sql import func

from app.core.db import Base


class LottoDrawORM(Base):
    """Stored Lotto draw metadata synchronized from DhLottery."""

    __tablename__ = "lotto_draws"

    draw_no = Column(Integer, primary_key=True)
    draw_date = Column(String(16), nullable=False)
    numbers = Column(JSON, nullable=False)
    bonus = Column(Integer, nullable=False)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(
        DateTime,
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class AnalysisSnapshotORM(Base):
    """Cached statistics results generated by /analysis endpoints."""

    __tablename__ = "analysis_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(128), nullable=False, index=True)
    max_draw_no = Column(Integer, nullable=False, default=0)
    created_at = Column(DateTime, server_default=func.now(), nullable=False, index=True)
    result = Column(JSON, nullable=False)
    metadata_json = Column(JSON, nullable=True)


class UserORM(Base):
    """Registered API user."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(64), nullable=False, unique=True, index=True)
    password_hash = Column(String(255), nullable=False)
    name = Column(String(128), nullable=False)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)


class RefreshTokenORM(Base):
    """Refresh tokens issued to a user."""

    __tablename__ = "refresh_tokens"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(
        String(64),
        ForeignKey("users.user_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    token = Column(String(512), nullable=False, unique=True, index=True)
    expires_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)


class UserTicketORM(Base):
    """User-submitted Lotto ticket evaluation history."""

    __tablename__ = "user_tickets"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(
        String(64),
        ForeignKey("users.user_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    draw_no = Column(Integer, nullable=False, index=True)
    numbers = Column(JSON, nullable=False)
    evaluation = Column(JSON, nullable=False)
    created_at = Column(DateTime, server_default=func.now(), nullable=False, index=True)
    updated_at = Column(
        DateTime,
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class RecommendationSnapshotORM(Base):
    """Cached recommendation results per draw/strategy."""

    __tablename__ = "recommendation_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy = Column(String(64), nullable=False)
    draw_no = Column(Integer, nullable=True)
    result = Column(JSON, nullable=False)
    updated_at = Column(
        DateTime,
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    __table_args__ = (
        UniqueConstraint("strategy", "draw_no", name="uq_strategy_draw_no"),
    )


class UserRecommendationORM(Base):
    """Saved recommendation per user/strategy/draw."""

    __tablename__ = "user_recommendations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(
        String(64),
        ForeignKey("users.user_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    strategy = Column(String(64), nullable=False)
    numbers = Column(JSON, nullable=False)
    draw_no = Column(Integer, nullable=False, index=True)
    evaluation = Column(JSON, nullable=True)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(
        DateTime,
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
    evaluated_at = Column(DateTime, nullable=True)

    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "draw_no",
            "strategy",
            name="uq_user_draw_strategy",
        ),
    )


__all__ = [
    "AnalysisSnapshotORM",
    "LottoDrawORM",
    "RecommendationSnapshotORM",
    "RefreshTokenORM",
    "UserORM",
    "UserRecommendationORM",
    "UserTicketORM",
]
