CREATE TABLE IF NOT EXISTS lotto_draws (
    draw_no INT NOT NULL,
    draw_date VARCHAR(16) NOT NULL,
    numbers JSON NOT NULL,
    bonus INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (draw_no)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
